name: utopia_recruitment_task
description: Zadanie rekrutacyjne Utopia USS
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.13
  cloud_firestore: ^3.1.11
  flutter_bloc: ^8.1.1
  formz: ^0.4.1
  equatable: ^2.0.5
  font_awesome_flutter: ^10.2.1
  another_flushbar: ^1.12.29
  intl: ^0.17.0
  mocktail: ^0.3.0
  bloc_test: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
